-- 1번 답
SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AVR IN (SELECT AVR FROM STUDENT WHERE MAJOR = '화학') AND MAJOR != '화학';

-- 3번 답
SELECT * FROM STUDENT WHERE (SYEAR, AVR) IN (SELECT SYEAR, AVR FROM STUDENT WHERE MAJOR = '화학') AND MAJOR != '화학';