-- 1번 답
SELECT * FROM PROFESSOR;
SELECT * FROM COURSE;
SELECT PROFESSOR.PNAME, COURSE.CNAME FROM PROFESSOR, COURSE WHERE PROFESSOR.PNO = COURSE.PNO AND PROFESSOR.PNAME = '송강';

-- 2번 답
SELECT * FROM PROFESSOR;
SELECT * FROM COURSE;
SELECT P.PNAME AS 화학_담당_교수 FROM PROFESSOR P, COURSE C WHERE p.pno = c.pno AND C.CNAME LIKE '%화학%';

-- 3번 답
SELECT * FROM PROFESSOR P, COURSE C WHERE P.PNO = C.PNO AND C.ST_NUM = 2;

-- 4번 답
SELECT * FROM STUDENT;
SELECT ST.SNO, ST.SNAME, ST.SYEAR, ST.MAJOR, SC.RESULT FROM STUDENT ST, SCORE SC WHERE ST.SNO = SC.SNO AND st.major = '화학' AND ST.SYEAR = 1;

-- 5번 답
SELECT * FROM SCORE;
SELECT * FROM COURSE;

-- 6번 답
SELECT C.CNAME, s.result FROM SCORE S, COURSE C WHERE S.CNO = C.CNO AND C.CNAME = '일반화학';

-- 9번 답
SELECT * FROM SCORE;
SELECT * FROM COURSE;
SELECT * FROM SCGRADE;
SELECT * FROM STUDENT;

WITH NC_SC AS(SELECT C.CNAME, S.SNO, S.RESULT FROM SCORE S, COURSE C WHERE S.CNO = C.CNO AND C.CNAME = '일반화학' AND S.RESULT BETWEEN 85 AND 100)
SELECT NC.CNAME, S.SNAME, NC.RESULT, CASE WHEN NC.RESULT IS NOT NULL THEN 'A' END AS GRADE FROM NC_SC NC, STUDENT S WHERE nc.sno = S.SNO;

-- 10번 답
SELECT * FROM COURSE;
SELECT * FROM PROFESSOR;
SELECT * FROM STUDENT;
SELECT * FROM score;

WITH SG_CLASS AS(SELECT C.CNO, P.PNAME FROM COURSE C, PROFESSOR P WHERE c.pno = P.PNO AND P.PNAME = '송강'),
SCORE_ONLY_SG_CLASS AS(SELECT sg_class.cno, score.sno, score.result FROM SG_CLASS, SCORE WHERE SG_CLASS.CNO = SCORE.CNO)
SELECT STUDENT.SNO, STUDENT.SNAME, score_only_sg_class.result FROM SCORE_ONLY_SG_CLASS, student WHERE score_only_sg_class.sno = STUDENT.SNO ORDER BY SCORE_ONLY_SG_CLASS.RESULT;

-- 11번 답
SELECT * FROM SCGRADE;
SELECT STUDENT.SNAME, 
    STUDENT.MAJOR, 
    STUDENT.SYEAR, 
    SCORE.RESULT, 
    CASE WHEN SCORE.RESULT BETWEEN 85 AND 100 THEN 'A' WHEN SCORE.RESULT BETWEEN 70 AND 84 THEN 'B' WHEN SCORE.RESULT BETWEEN 55 AND 69 THEN 'C' WHEN SCORE.RESULT BETWEEN 40 AND 54 THEN 'D' ELSE 'F' END AS GRADE
FROM STUDENT, SCORE WHERE STUDENT.SNO = SCORE.SNO AND student.syear = 1 AND STUDENT.MAJOR = '화학';

-- 13번 답
SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM SCORE;
SELECT * FROM PROFESSOR;

WITH CHEMICAL_STUDENT AS(SELECT * FROM STUDENT WHERE syear = 1 AND major = '화학'),
     CHEMICAL_STUDENT_SCORE AS(SELECT SCORE.SNO,  CHEMICAL_STUDENT.SNAME, SCORE.RESULT, SCORE.CNO FROM CHEMICAL_STUDENT, SCORE WHERE CHEMICAL_STUDENT.SNO = SCORE.SNO),
     PROFESSOR_FOR_1YEAR_CHEMICAL_STUDENT AS(SELECT DISTINCT course.pno FROM CHEMICAL_STUDENT_SCORE, COURSE WHERE CHEMICAL_STUDENT_SCORE.CNO = course.cno)
SELECT professor.pname FROM PROFESSOR_FOR_1YEAR_CHEMICAL_STUDENT, PROFESSOR WHERE professor_for_1year_chemical_student.pno = professor.pno;


