 CREATE TABLE TEST_CUST_MST
 (
 CUST_NO NUMBER,
 CUST_NM VARCHAR2(255),
 GROUP_NO NUMBER,
 CONSTRAINT TEST_CUST_MST_PK PRIMARY KEY(CUST_NO)
 );
 
 INSERT INTO TEST_CUST_MST VALUES(2001, 'KIM', 2);
 INSERT INTO TEST_CUST_MST VALUES(1000, 'PARK', 1);
 INSERT INTO TEST_CUST_MST VALUES(2000, 'LEE', 2);
 INSERT INTO TEST_CUST_MST VALUES(3000, 'LIM', 3);
 INSERT INTO TEST_CUST_MST VALUES(999, 'CHOI', 1);
 
 CREATE TABLE TEST_GROUP_MST
 (
    GROUP_NO NUMBER,
    GROUP_NM VARCHAR2(255),
    CONSTRAINT TEST_GROUP_MST_PK PRIMARY KEY(GROUP_NO)
 );
 
 INSERT INTO TEST_GROUP_MST VALUES(1, '무료');
 INSERT INTO TEST_GROUP_MST VALUES(2, '일반');
 INSERT INTO TEST_GROUP_MST VALUES(3, '고급');
 
 COMMIT ;
 
SELECT /*+ INDEX(TEST_CUST_MST TEST_CUST_MST_PK)*/ *
FROM TEST_CUST_MST A, TEST_GROUP_MST B
WHERE A.group_no = B.GROUP_NO AND
      A.CUST_NO >= 2000;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(null, null, 'ALLSTATS LAST'));
 
DECLARE
      V_CNT NUMBER := 3000;    --초기값
BEGIN
    LOOP
    EXIT WHEN V_CNT = 3100;       --조건 (V_CNT가 10이되면 LOOP끝)
      
      V_CNT := V_CNT + 1;       --증가치 (1씩증가)

      INSERT INTO WITH_TEST VALUES(V_CNT, 'KO');
    END LOOP;
END;
 DROP TABLE TEST_CUST_MST;

WITH A AS (
SELECT  *
FROM WITH_TEST
)
SELECT /*+ INDEX(WITH_TEST WITH_TEST_PK) */ *
FROM A
WHERE CUST_NO >= 2000;

