-- 각 세션의 입구 페이지와 출구 페이지 경로를 추출하는 쿼리

SELECT SESSION_ID,
       STAMP,
       PATH,
       FIRST_VALUE(PATH) OVER(PARTITION BY SESSION_ID ORDER BY STAMP ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LANDING_PAGE,
       LAST_VALUE(PATH) OVER(PARTITION BY SESSION_ID ORDER BY STAMP ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)  AS EXIT_PAGE
FROM ACTIVITY_LOG
;

-- 입구 페이지와 출구 페이지 조합별 COUNT를 집계하는 쿼리

SELECT LANDING_PAGE,
       EXIT_PAGE,
       COUNT(DISTINCT SESSION_ID) AS CNT
FROM (
    SELECT SESSION_ID,
           STAMP,
           PATH,
           FIRST_VALUE(PATH) OVER(PARTITION BY SESSION_ID ORDER BY STAMP ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LANDING_PAGE,
           LAST_VALUE(PATH) OVER(PARTITION BY SESSION_ID ORDER BY STAMP ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)  AS EXIT_PAGE
    FROM ACTIVITY_LOG
)
GROUP BY LANDING_PAGE, EXIT_PAGE
;

-- 경로별 이탈률을 집계하는 쿼리

SELECT PATH,
       SUM(FLAG_OF_EXIT_PAGE_BY_SESSION)                    AS EXIT_PAGE_CNT,
       COUNT(1)                                             AS VIEW_CNT,
       (SUM(FLAG_OF_EXIT_PAGE_BY_SESSION) / COUNT(1)) * 100 AS EXIT_RATIO
FROM (
    SELECT SESSION_ID,
           STAMP,
           PATH,
           CASE 
                WHEN ROW_NUMBER() OVER(PARTITION BY SESSION_ID ORDER BY STAMP DESC) = 1 THEN 1
                ELSE 0
           END AS FLAG_OF_EXIT_PAGE_BY_SESSION
    FROM   ACTIVITY_LOG
)
GROUP BY PATH
;

-- 컨버전(전환[구매완료]) PATH까지 도달하는 여정 內 존재하는 모든 PATH에 플래그를 추가하는 쿼리
-- (컨버전 PATH 이후에 존재하는 PATH들에 대해선 '0'을 부여함)

SELECT SESSION_ID,
       STAMP,
       PATH,
       SIGN(SUM(CASE WHEN PATH = '/complete' THEN 1 ELSE 0 END) OVER(PARTITION BY SESSION_ID ORDER BY STAMP DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) AS IS_CONVERSION
FROM ACTIVITY_LOG
ORDER BY SESSION_ID, STAMP
;

-- PATH별 세션 방문 횟수, 컨버전 기여 횟수, CVR을 집계하는 쿼리

SELECT PATH,
       SUM(IS_CONVERSION) AS CONVERSION_CNT,
       COUNT(DISTINCT SESSION_ID) AS SESSION_ACCESS_CNT,
       FLOOR((SUM(IS_CONVERSION) / COUNT(DISTINCT SESSION_ID)) * 100) AS CVR
FROM (
    SELECT SESSION_ID,
           STAMP,
           PATH,
           SIGN(SUM(CASE WHEN PATH = '/complete' THEN 1 ELSE 0 END) OVER(PARTITION BY SESSION_ID ORDER BY STAMP DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) AS IS_CONVERSION
    FROM ACTIVITY_LOG
    ORDER BY SESSION_ID, STAMP
)
GROUP BY PATH
;